# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-wwindows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Step 1 Log the pre-build disc space
        run: ls
        
      - name: Step 2 Check out to main github branch
        uses: actions/checkout@v2
        
    # - name: Step 3 Set up JDK 1.8
  
      - name: Step 5 Check windows execution policy
        run: |
          echo Here is the windows execution policy
          Get-ExecutionPolicy
        
      - name: Step 6 Windows environment vaiables
        run: env
  

